# -*- coding: utf-8 -*-
"""Curated list of Chinese cities with airports, for route-editor autocomplete.

支持去哪儿任意中文城市名直输;此列表仅用于输入联想(中文名/全拼/首字母),
避免手输偏差。需要更多城市直接往 CITIES 里加一行即可。
"""

CITIES = [
    {"name": "北京", "pinyin": "beijing", "py": "bj"},
    {"name": "上海", "pinyin": "shanghai", "py": "sh"},
    {"name": "广州", "pinyin": "guangzhou", "py": "gz"},
    {"name": "深圳", "pinyin": "shenzhen", "py": "sz"},
    {"name": "成都", "pinyin": "chengdu", "py": "cd"},
    {"name": "重庆", "pinyin": "chongqing", "py": "cq"},
    {"name": "杭州", "pinyin": "hangzhou", "py": "hz"},
    {"name": "南京", "pinyin": "nanjing", "py": "nj"},
    {"name": "武汉", "pinyin": "wuhan", "py": "wh"},
    {"name": "西安", "pinyin": "xian", "py": "xa"},
    {"name": "长沙", "pinyin": "changsha", "py": "cs"},
    {"name": "郑州", "pinyin": "zhengzhou", "py": "zz"},
    {"name": "昆明", "pinyin": "kunming", "py": "km"},
    {"name": "大理", "pinyin": "dali", "py": "dl"},
    {"name": "丽江", "pinyin": "lijiang", "py": "lj"},
    {"name": "贵阳", "pinyin": "guiyang", "py": "gy"},
    {"name": "兰州", "pinyin": "lanzhou", "py": "lz"},
    {"name": "西宁", "pinyin": "xining", "py": "xn"},
    {"name": "银川", "pinyin": "yinchuan", "py": "yc"},
    {"name": "乌鲁木齐", "pinyin": "wulumuqi", "py": "wlmq"},
    {"name": "拉萨", "pinyin": "lasa", "py": "ls"},
    {"name": "哈尔滨", "pinyin": "haerbin", "py": "heb"},
    {"name": "长春", "pinyin": "changchun", "py": "cc"},
    {"name": "沈阳", "pinyin": "shenyang", "py": "sy"},
    {"name": "大连", "pinyin": "dalian", "py": "dl"},
    {"name": "天津", "pinyin": "tianjin", "py": "tj"},
    {"name": "石家庄", "pinyin": "shijiazhuang", "py": "sjz"},
    {"name": "太原", "pinyin": "taiyuan", "py": "ty"},
    {"name": "呼和浩特", "pinyin": "huhehaote", "py": "hhht"},
    {"name": "南昌", "pinyin": "nanchang", "py": "nc"},
    {"name": "福州", "pinyin": "fuzhou", "py": "fz"},
    {"name": "厦门", "pinyin": "xiamen", "py": "xm"},
    {"name": "泉州", "pinyin": "quanzhou", "py": "qz"},
    {"name": "合肥", "pinyin": "hefei", "py": "hf"},
    {"name": "青岛", "pinyin": "qingdao", "py": "qd"},
    {"name": "济南", "pinyin": "jinan", "py": "jn"},
    {"name": "烟台", "pinyin": "yantai", "py": "yt"},
    {"name": "威海", "pinyin": "weihai", "py": "wh"},
    {"name": "温州", "pinyin": "wenzhou", "py": "wz"},
    {"name": "宁波", "pinyin": "ningbo", "py": "nb"},
    {"name": "义乌", "pinyin": "yiwu", "py": "yw"},
    {"name": "珠海", "pinyin": "zhuhai", "py": "zh"},
    {"name": "桂林", "pinyin": "guilin", "py": "gl"},
    {"name": "南宁", "pinyin": "nanning", "py": "nn"},
    {"name": "北海", "pinyin": "beihai", "py": "bh"},
    {"name": "海口", "pinyin": "haikou", "py": "hk"},
    {"name": "三亚", "pinyin": "sanya", "py": "sy"},
    {"name": "汕头", "pinyin": "shantou", "py": "st"},
    {"name": "揭阳", "pinyin": "jieyang", "py": "jy"},
    {"name": "常州", "pinyin": "changzhou", "py": "cz"},
    {"name": "无锡", "pinyin": "wuxi", "py": "wx"},
    {"name": "徐州", "pinyin": "xuzhou", "py": "xz"},
    {"name": "扬州", "pinyin": "yangzhou", "py": "yz"},
    {"name": "南通", "pinyin": "nantong", "py": "nt"},
    {"name": "张家界", "pinyin": "zhangjiajie", "py": "zjj"},
    {"name": "襄阳", "pinyin": "xiangyang", "py": "xy"},
    {"name": "宜昌", "pinyin": "yichang", "py": "yc"},
    {"name": "恩施", "pinyin": "enshi", "py": "es"},
    {"name": "遵义", "pinyin": "zunyi", "py": "zy"},
    {"name": "延吉", "pinyin": "yanji", "py": "yj"},
    {"name": "敦煌", "pinyin": "dunhuang", "py": "dh"},
    {"name": "喀什", "pinyin": "kashi", "py": "ks"},
    {"name": "伊宁", "pinyin": "yining", "py": "yn"},
    {"name": "呼伦贝尔", "pinyin": "hulunbeier", "py": "hlbe"},
    {"name": "长白山", "pinyin": "changbaishan", "py": "cbs"},
    {"name": "景德镇", "pinyin": "jingdezhen", "py": "jdz"},
    {"name": "黄山", "pinyin": "huangshan", "py": "hs"},
    {"name": "洛阳", "pinyin": "luoyang", "py": "ly"},
]

